name: PR Label Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const requiredLabels = ["feat", "fix", "docs", "style", "refractor", "perf", "test", "build", "ci", "chore", "revert"];
            const labels = context.payload.pull_request.labels.map(label => label.name);
            const missingLabels = requiredLabels.filter(label => !labels.includes(label));

            if (labels.length == 0) {
              core.setFailed(`Missing required labels`);
            }
