name: Verify PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  verify_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title
        id: title_check
        run: |
          title=$(echo "${{ github.event.pull_request.title }}" | tr '[:upper:]' '[:lower:]')
          prValidation=true
          if [[ ! $title =~ (fix|feature|feat|docs|style) ]]; then
            prValidation=false
            
          fi

      - name: Create Comment
        if: prValidation=false
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const comment = `
            this will execute if pr dose not have any title

            `;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })
