name: Verify PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  verify_pr:
    runs-on: ubuntu-latest
    env:
      LABEL_VALIDATION: true
    steps:
      - name: Check PR Title
        id: title_check
        run: |
          title=$(echo "${{ github.event.pull_request.title }}" | tr '[:upper:]' '[:lower:]')
          if [[ ! $title =~ (fix|feature|feat|docs|style) ]]; then
            echo "{LABEL_VALIDATION}={false}" >> "$GITHUB_ENV"  
          fi

      - name: Create Comment
        if: ${{ env.LABEL_VALIDATION == 'false' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            this dosent have any lable in title

      - name: Delete Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: check-pr-title
          delete: true 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
